hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
metafile = true

[[files]]
file = "mods/ad-astra.pw.toml"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/architects-palette.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/armourers-workshop.pw.toml"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
metafile = true

[[files]]
file = "mods/athena.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/better-chunk-loading-forge-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/better-fps-render-distance.pw.toml"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/builders-delight.pw.toml"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/chisels-bits.pw.toml"
metafile = true

[[files]]
file = "mods/chunk-sending-forge-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/client-crafting.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
metafile = true

[[files]]
file = "mods/configured.pw.toml"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
metafile = true

[[files]]
file = "mods/create-clockwork.pw.toml"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
metafile = true

[[files]]
file = "mods/create-design-n-decor.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
metafile = true

[[files]]
file = "mods/customskinloader.pw.toml"
metafile = true

[[files]]
file = "mods/decorative-blocks.pw.toml"
metafile = true

[[files]]
file = "mods/domum-ornamentum.pw.toml"
metafile = true

[[files]]
file = "mods/dramatic-doors.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
metafile = true

[[files]]
file = "mods/dynamic-view.pw.toml"
metafile = true

[[files]]
file = "mods/dynamiclights-reforged.pw.toml"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
metafile = true

[[files]]
file = "mods/effortless-building.pw.toml"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
metafile = true

[[files]]
file = "mods/embeddiumplus.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/eureka.pw.toml"
metafile = true

[[files]]
file = "mods/fairy-lights.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/farsight.pw.toml"
metafile = true

[[files]]
file = "mods/fast-async-world-save-forge-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/fix-gpu-memory-leak.pw.toml"
metafile = true

[[files]]
file = "mods/framedblocks.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/geophilic.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
metafile = true

[[files]]
file = "mods/joy-of-painting.pw.toml"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "mods/krypton-reforged.pw.toml"
metafile = true

[[files]]
file = "mods/leaky.pw.toml"
metafile = true

[[files]]
file = "mods/limited-chunkloading.pw.toml"
metafile = true

[[files]]
file = "mods/littlepictureframes.pw.toml"
metafile = true

[[files]]
file = "mods/littletiles.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-holidays.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
metafile = true

[[files]]
file = "mods/mcef.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/mrcrayfish-furniture-mod.pw.toml"
metafile = true

[[files]]
file = "mods/music-maker-mod.pw.toml"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled-create.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
metafile = true

[[files]]
file = "mods/smooth-boot-reloaded.pw.toml"
metafile = true

[[files]]
file = "mods/smooth-chunk-save.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/valkyrien-skies.pw.toml"
metafile = true

[[files]]
file = "mods/video-player.pw.toml"
metafile = true

[[files]]
file = "mods/waterframes.pw.toml"
metafile = true

[[files]]
file = "mods/watermedia.pw.toml"
metafile = true

[[files]]
file = "mods/world-preview.pw.toml"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
metafile = true

[[files]]
file = "mods/xks-decoration.pw.toml"
metafile = true

[[files]]
file = "mods/yuushya-modelling.pw.toml"
metafile = true

[[files]]
file = "mods/yuushya-townscape.pw.toml"
metafile = true
