name = "Modpack Criativo"
author = "pvini07BR"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94e38bfc9e8ff1d7c6e7792939ffa541831e862d17884895b2de0d959da4293e"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
