name = "Modpack Criativo"
author = "pvini07BR"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "120399df3d52a8a59b99388862fefb0e46615fc05ad0b3733f4df76908461050"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
no-internal-hashes = true
