name = "Modpack Criativo"
author = "pvini07BR"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1180c88f21dc5339fc3f63ed6e48ead775d874fa69c65635d4dcdc89ad473c57"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
no-internal-hashes = true
