name = "Modpack Criativo"
author = "pvini07BR"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ed8e381a502ee42cb41d01a5cbba54ad10f8992986fa6eedca59ba176044938"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
